name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment for Backend
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        npm install
        echo "Skipping tests as they are not defined"

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newamericans-demo' # Replace with your Azure App Service name
        slot-name: 'production' # Use 'production' or omit if not using slots
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0AF4B34949514083BC707055344C26ED }}
        package: '.'

